<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- NuGet package metadata -->
    <PackageId>VinTest.Cake</PackageId>
    <Version>0.1.0</Version>
    <Description>Cake tasks for automating VintageStory mod game tests with VinTest.</Description>
    <PackageTags>VintageStory modding testing cake</PackageTags>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cake.Common" Version="6.1.0" />
    <PackageReference Include="Cake.Frosting" Version="6.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
</Project>
